### ISSUE TITLE
FakeSIRTiteration parameter

### ISSUE THREAD

**Issue by ssscj** [turonova/novaCTF#10]
Hi, thanks for developing these useful tools. I want to use the FakeSIRTiteration, but I don't know where to use it. For in IMOD, this parameter is used in reconstruction step 'tilt', and in the wiki of novaCTF, it is in the Filtering part. Thank you.

**Comment by turonova** [comment]
Hi,

that's correct - the FakeSIRTIteration parameter concerns filtering which is done as a part of the tilt function in IMOD. However, in novaCTF the filtering is separated and thus this parameter should be used there.
