### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by pconesa** [turonova/novaCTF#15]
Hi I'd like to know if this code is supported? or if it's frozen.

@turonova , may be you moved to git lab?

All the best, Pablo.

**Comment by turonova** [comment]
Hi,


no, the code is active in the sense that it is the newest version I have.
There will be some updates coming soon but for now there is nothing newer
out there - at least not from me.


Best,


Beata Turonova

st 20. 5. 2020 v 15:41 odesílatel Pablo Conesa <notifications@github.com>
napsal:

**Comment by pconesa** [comment]
Thanks! We are integrating this into Scipion for tomography. You are very welcome to assist in the integration.
