### ISSUE TITLE
*.rec has unknown format.

### ISSUE THREAD

**Issue by ncoudray** [turonova/novaCTF#18]
Hi,

  I've been running the different steps without getting any error message, and the final *rec reconstruction went to completion as well, but I tried to open it (with imod, or e2display), it fails to recognize the file. With imod for example it says:
"ERROR: iiOpen - novactf_19oct06a_series0003.rec has unknown format."

 Any idea what could have gone wrong? 

Thanks,
Best,
Nicolas

**Comment by ncoudray** [comment]
Hi - to give more information: this was compiled with gcc 6.1.0 on red hat 7.9
The files from the previous step (filterProjections) seem to be ok (those can be read with imod)

Thanks
N.

**Comment by XiaJia98** [comment]
Hi Ncoudray,

Did you get an answer? I have the same question as you are.

Thanks,
Rainbow Xia Jia

**Comment by ncoudray** [comment]
Hi - In the last step, I would suggest to check the volume thickness - I think it is in nm, not in Angstrom (if you put a value too high, you may have lots of files generates and this type of error).
Best,
N.

**Comment by XiaJia98** [comment]
> 

Hi, Nicolas:

It has worked, thanks a lot.

Best,

Xia Jia
