### ISSUE TITLE
defocus file

### ISSUE THREAD

**Issue by sdhindwal** [turonova/novaCTF#2]
Hi,

I am new to the program novaCTF and I want to use novaCTF for CTF estimation and CTF correction for few tomograms that I have collected. I want to request you to please provide the format of defocus_file.txt to be used to run the first step "generate defocus files". I want to use ctffind program for CTF estimation. I want to know how to specify the defocus values and step size.
Thanks in advance.

Regards

**Comment by turonova** [comment]
Hi,

there are two formats of defocus files you can use. One corresponds to the one produced by IMOD CTF estimation (description of this format can be found here http://bio3d.colorado.edu/imod/doc/man/ctfphaseflip.html). The second corresponds to the standard CTFFind4 output. Typically, the files starts with some description of parameters and is followed by number of lines each of which corresponds to one tilt in your input stacks:

\# Output from CTFFind version 4.1.8, run on 2017-10-09 18:26:28
\# Input file: 47.mrc ; Number of micrographs: 41
\# Pixel size: 3.350 Angstroms ; acceleration voltage: 300.0 keV ; spherical aberration: 2.70 mm ; amplitude contrast: 0.07
\# Box size: 512 pixels ; min. res.: 30.0 Angstroms ; max. res.: 5.0 Angstroms ; min. def.: 5000.0 um; max. def. 55000.0 um
\# Columns: #1 - micrograph number; #2 - defocus 1 [Angstroms]; #3 - defocus 2; #4 - azimuth of astigmatism; #5 - additional phase shift [radians]; #6     - cross correlation; #7 - spacing (in Angstroms) up to which CTF rings were fit successfully
1.000000 31500.015625 31000.015625 45.000008 0.000000 -0.008399 15.881481
.
.
.

If you use CTFFind4 you can directly use its *.txt output in novaCTF and you do not have to change anything in that file (you have to specify the defocus file type to be ctffind4, details on how to do that can be found in the parameters section in wiki).

As for the step size - this is data specific and depends both on the resolution you hope to get and on the confidence of CTF estimation. Useful graph that might help with the decision can be found in the paper on novaCTF.

**Comment by sdhindwal** [comment]
Hi Thanks for the reply. I was able to get defocus file using the CTFFind4. After the first step: generating the defocus file, gave me 41 files with defocus.txt_#. Please let me know if this is the correct output. 

It will great if you could upload an example with the output file. It would be easier to understand and use the software. Thanks again for the help.

**Comment by turonova** [comment]
The number of defocus files depends on the defocus step size but also on the thickness of tomograms and the min/max tilt angles - the corner points of the tomogram are rotated by min/max angle to get the effective thickness of the tomogram and this thickness is then divided by the defocus step size into "slices", the number of those slices correspond to the number of the output defocus files. 

The output is always odd number of files - the middle one (in your case #20) should have the same values as the input one (unless you used DefocusShiftFile option). The only difference would be lack of the header lines (starting with #). The rest of the files have just shifts applied to both defocus values, other values should be the same as in the input file.
