### ISSUE TITLE
Output ctf corrected stack

### ISSUE THREAD

**Issue by hongzhan2015** [turonova/novaCTF#5]
Hihi, 
I have wired ctf corrected stack. i can see the strips on board and also in some of my structure... Is this normal?

Thanks!!

Best,
Hong
<img width="592" alt="screen shot 2017-11-17 at 12 23 09 pm" src="https://user-images.githubusercontent.com/12883636/32964950-259368e2-cb92-11e7-961f-d6b7e44c6dc2.png">

**Comment by turonova** [comment]
No it is not normal and it is most likely caused by having non-squared images. I am currently working on fixing this issue but in the meantime try to crop your images to have same dimensions in x and y - this artifact should then disappear.

**Comment by turonova** [comment]
I have just uploaded (hopefully) corrected version. Please download novaCTF from github website again and try whether the artifacts disappear.

**Comment by hongzhan2015** [comment]
Thanks!! indeed... my image is 3710x3838... I will download and get update you.

Many thanks!

**Comment by hongzhan2015** [comment]
Hihi, 
I got correct stack! many thanks!

Hong
