### ISSUE TITLE
Z shifts and angle offset in novaCTF

### ISSUE THREAD

**Issue by SteinarHall** [turonova/novaCTF#9]
Hi developers

I am having some trouble with figuring out how to shift my tomograms.
In the Reconstruction part of the tomogram there is Shift option which takes in two numbers. What are these parameters?
I've been trying to reconstruct tomograms which I have previously done in etomo and I would like to recreate it in the same way. From etomo, if I try using the parameters Angle offset and Z shift (found in Tomogram Positioning) as the two Shift inputs, it doesn't reconstruct it in the right way.
Are there parameters from a previous reconstruction in etomo that you can use?

Thanks a lot!
Steinar

P.S. The software is really useful and seems to create tomograms of high quality.

**Comment by turonova** [comment]
Hi,

the SHIFT parameter takes two values, first one is shift in X, the second one is Z shift and that is the one you want to use. I believe the angle offset is stored in OFFSET but I am not entirely sure if this is the one you mean.  For detailed parameter description you can check the [tilt man page](http://bio3d.colorado.edu/imod/doc/man/tilt.html) from IMOD.

If you open in your eTomo folder tilt.com file (with text editor) you will be able to see all the parameters you used to reconstruct in eTomo. You can directly fetch this file to novaCTF using -param tilt.com command (if you want to change something like e.g. input projections name you can either change it directly in tilt.com or pass it normally through command line, the command line parameters have higher priority and will overwrite those from tilt.com). All the parameters that are not supported in novaCTF will be simply ignored (and message will be written out about that).

**Comment by SteinarHall** [comment]
Hi Turanova

Thanks for the advice. The tilt.com file was very useful for recreating a similar tomogram. Unfortunately novaCTF doesn't take in XAXISTILT (either straight in the command line or in the tilt.com file) so I couldn't recreate exactly the tomogram, but that's not such a tragedy.

Thanks again!
Steinar
